#!/usr/bin/env sh
DIR=`pwd`/quickstart
mkdir -p $DIR/voting-keys
nix-shell --run "\
  vvvote-admin.sh createKeyPair p 1 $DIR && \
  vvvote-admin.sh createKeyPair p 2 $DIR && \
  vvvote-admin.sh createKeyPair t 1 $DIR && \
  vvvote-admin.sh createKeyPair t 2 $DIR"
nix-build --arg customVarsPath ./quickstart_vars_server_1.nix -o $DIR/server1
nix-build --arg customVarsPath ./quickstart_vars_server_2.nix -o $DIR/server2
cd $DIR

trap 'kill $(jobs -p)' EXIT
$DIR/server1/bin/vvvote-backend.sh > vvvote_server_1.log &
$DIR/server2/bin/vvvote-backend.sh > vvvote_server_2.log &
wait
